name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build application
        run: |
          # Commandes pour compiler votre application Java
          javac -d target src/junit/monprojet/*.java

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Install JUnit
        run: |
          # Commandes pour installer JUnit
          mkdir lib
          curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
          mv junit-platform-console-standalone-1.8.2.jar lib/

      - name: Run automated tests
        run: |
          # Commandes pour exécuter les tests automatisés avec JUnit
          java -jar lib/junit-platform-console-standalone-1.8.2.jar --class-path target --scan-class-path

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [test] # Ce job dépend du job 'test'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to production
        run: |
          # Commandes pour déployer votre application dans un environnement de production
          # Exemple: Utiliser des outils comme Docker, Ansible, ou simplement copier les fichiers sur un serveur
