name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build application
        run: |
          mkdir -p target
          javac -d target src/junit/monprojet/*.java

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install JUnit
        run: |
          mkdir -p lib
          curl -O https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
          mv junit-platform-console-standalone-1.8.2.jar lib/

      - name: Run automated tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.8.2.jar --classpath target --scan-classpath

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to production
        run: |
          # Commandes pour déployer votre application dans un environnement de production
          # Exemple: Utiliser des outils comme Docker, Ansible, ou simplement copier les fichiers sur un serveur
          echo "Ajoutez ici les commandes de déploiement nécessaires"
